---
title : "`r substr(toupper(params$opco), 1, 2)`"
output: 
  flexdashboard::flex_dashboard:
    theme: cosmo
    navbar:
      - { title: "Data Catalog", href: "http://report.grandvision.global/bi-doc/udc", align: right }
    orientation: columns
    vertical_layout: fill
params:
  denv : "prd"    # environment acc | prd
  opco : "ch"     # 2 character opco
  nrws : "Inf"    # c(-1,0,1,n)
---

```{r setup, include=FALSE}
# this file sources all other scripts
source(file.path("~", "isdb", "00-scripts", "00_setup.R"))
opco_labels <- f_read_opco_labels()
```

```{r read_data, eval=TRUE}
system.time({
  
# read nrows from all tables 
raw_data <-
  f_read_opco_data(
    denv = params$denv,                    # environment acc | prd
    opco = params$opco,                    # 2 character opco    
    ds   = c("ARTICLE"),                   # specific Data Sources
    nrws = as.numeric(params$nrws)         # c(-1,0,1,n)
  ) 

})


# SO <- raw_data[["SELL_OUT"]][, .(Q = sum(QUANTITY)), by = .(LOCAL_ARTICLE_ID)]
# 
# ARTICLE_FRAME_AND_SUN <- 
#   SO[ARTICLE_FRAME_AND_SUN, on = .(LOCAL_ARTICLE_ID),
#      nomatch = 0]


# write.csv2(
#   ARTICLE_FRAME_AND_SUN, 
#   paste0("../60-results/", params$opco, "_articleQ.csv"))


# raw_data[["SELL_OUT"]] <- 
#   ARTICLE_FRAME_AND_SUN[raw_data[["SELL_OUT"]], 
#                         on = .(LOCAL_ARTICLE_ID), nomatch = 0] %>%
#   .[, `:=` (Purchase_Price       = COGS/QUANTITY,
#             Retail_Price_inc_VAT = GROSS_VALUE_SALES_INC_VAT/QUANTITY,
#             Retail_Price_ex_VAT  = GROSS_VALUE_SALES_EX_VAT/QUANTITY)] 
# # %>%
# #   .[ISVALID                == 1  &
# #       RETURN_INDICATOR       == "0" &
# #       CANCELLATION_INDICATOR == "0", ]
# 
# raw_data[["DISCOUNTS"]] <- 
#   raw_data[["DISCOUNTS"]][raw_data[["SELL_OUT"]],
#                           on = .(LINK_TO_TICKET_ID_LINE == TICKET_ID_LINE,
#                                  STORE_ID, TICKET_ID)]

# read metadata_didp
metadata_didp <-
  f_read_meta_data(opco = params$opco)     # 2 character opco


```

```{r determine_factors, eval=F}

# Check Primary Keys
primary_key <- 
  f_check_primkeys(
    lst_raw_data     = raw_data,
    dt_metadata_didp = metadata_didp
  )

f_write_primary_key_log(primary_key)

raw_data <- 
  f_remove_duplicates(
    primary_key = primary_key,
    lst_raw_data = raw_data
  )




# TAB <- "ARTICLE"
# 
# system.time(
#   tst3 <- f_analyze_tables(raw_data[TAB])
#   )
# 
# dtDSTATS <- 
#   lapply(names(tst3[[TAB]]), f_get_column_analysis, 
#          .lst= tst3, .table = TAB, .resultset = "DSTATS") %>% 
#   rbindlist() %>%
#   .[, SOURCE := TAB]


```

```{r graph_purchase-price, eval=FALSE}
x <- 
  raw_data[["SELL_OUT"]] %>%
  .[, .(Category = factor(CATEGORY_NAME), PP = COGS/QUANTITY)] %>% 
  .[PP <= 0, PP:= 0.01 ] %>%
  .[is.nan(PP) , PP:= 0.01 ]

gvColors <- 
  c(GV_BLUE_0, GV_ORNG_0)

names(gvColors) <- 
  levels(x$Category)

colScale <- 
  scale_fill_manual(name = "Category", values = gvColors)

p1 <- 
  ggplot(data = x, 
         mapping = aes(x = Category, y = PP, 
                       fill = Category))
(p2 <- 
  p1 + 
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) + 
  scale_y_log10(breaks = c(0.1, 10, 50, 100, 500, 1000, 10000)) + 
  colScale +
  labs(x = "Category", y = "Purchase price"))
```

ISVALID == 1 & RETURN_INDICATOR == 0 & CANCELLATION_INDICATOR == 0

```{r graph_gan_mapping, eval=FALSE}
path <- 
  file.path("..", "80-figures", "pmdm_mapping") %>%
  f_get_folder()

# inner-join frame & Sun and add MD attributes
x <- 
  raw_data[["SELL_OUT"]] %>%
  ARTICLE_FRAME_AND_SUN[, .(LOCAL_ARTICLE_ID, CATEGORY_CODE, MAP) ][
    ., on = .(LOCAL_ARTICLE_ID), nomatch = 0 ] %>%
  .[, .(Q = sum(QUANTITY), V = sum(GROSS_VALUE_SALES_INC_VAT)), 
    by = .(Month    = floor_date(ymd(DATE), "month"), 
           Category = factor(
             CATEGORY_CODE, labels = c("Frames", "Sunglasses")), 
           MAP)] 

# map the GV-colors 
#                    "-"      , MARA_EAN , PMDM_EAN , PMDM_GAN
gvColors        <- c(GV_ORNG_0, GV_GREY_1, GV_BLUE_2, GV_BLUE_0)
names(gvColors) <- levels(x$MAP)
colScale        <- scale_fill_manual(name = "pmdm", values = gvColors)
colScale_col    <- scale_color_manual(name = "pmdm", values = gvColors)

# Determine the breaks
db <- paste(ceiling(length(unique(x$Month))/9), "month")
br <- (1:10)/10
et <- element_text(
      family = "DejaVu Sans", face = "plain", colour = GV_GREY_1, size = 15)
at <- element_text(
      family = "DejaVu Sans", face = "plain", colour = GV_GREY_1, size = 12)

# Map data, aesthetics, GV colors and time scale
pQ <- 
  ggplot(data = x, mapping = aes(x = Month, y = Q, fill = MAP)) +
  colScale + 
  scale_x_date(date_breaks = eval(db), date_labels = "%Y.%m") +
  scale_y_continuous(sec.axis = sec_axis(~ . )) +
  # labs(title = paste0(params$opco ), x = "Date") +
  labs(
    title = opco_labels[OPCO == params$opco, LABEL], 
    subtitle = format(today(), "%A, %d %B, %Y "),
    x = "Date") +  
  facet_wrap(facets = "Category", nrow = 2) +
  theme(text = at, title = et, legend.position = "bottom")

# Plot Identity
(pQI <- 
    pQ + 
    geom_col() +                             # legend.position="top"
    # geom_hline(
    #   data = x[, .(yintercept = mean(Q)), by = .(Category, MAP)], 
    #   mapping= aes(yintercept = yintercept, color = MAP)) +
    # colScale_col +
    labs(y = "Sell-Out Vol. ")
  ) 
# save plot per day
ggsave(plot = pQI, 
       file.path(path, paste0(params$opco, "_qi_", today(), ".png")))

x_mean_cumQ <- 
  copy(x) %>%
  .[, .(tot = sum(Q)), by = .(Category, MAP)] %>%
  .[, yintercept:= tot/sum(tot), by = .(Category)] %T>%
  setorder(Category, -MAP) %>%
  .[, yintercept:=cumsum(yintercept), by = .(Category)]

# Plot Percentage 
(pQP <- pQ + geom_col(position = position_fill())  + 
    labs(y = "Sell-Out Vol. % ") +
    geom_hline(
      data = x_mean_cumQ, 
      mapping= aes(yintercept = yintercept, color = MAP), linetype = "dashed", size = 1) +
    colScale_col +
    scale_y_continuous(
      labels = scales::percent_format(), breaks = br,
  sec.axis = sec_axis(~ ., labels = scales::percent_format(), breaks = br )))
# save plot per day
ggsave(plot = pQP, 
       file.path(path, paste0(params$opco, "_qp_", today(), ".png")))

pV <- 
  ggplot(data = x, mapping = aes(x = Month, y = V, fill = MAP)) +
  colScale + 
  scale_x_date(date_breaks = eval(db), date_labels = "%Y.%m") +
  scale_y_continuous(sec.axis = sec_axis(~ . )) +  
  # labs(title = paste0(params$opco ), x = "Date") +
  labs(
    title = opco_labels[OPCO == params$opco, LABEL], 
    subtitle = format(today(), "%A, %d %B, %Y "),
    x = "Date") +    
  facet_wrap(facets = "Category", nrow = 2) +
  theme(text = at, title = et, legend.position = "bottom")

# Plot Identity
(pVI <- pV + geom_col() + labs(y = "Sell-Out Val. "))   
# save plot per day
ggsave(plot = pVI, 
       file.path(path, paste0(params$opco, "_vi_", today(), ".png")))

x_mean_cumV <- 
  copy(x) %>%
  .[, .(tot = sum(V)), by = .(Category, MAP)] %>%
  .[, yintercept:= tot/sum(tot), by = .(Category)] %T>%
  setorder(Category, -MAP) %>%
  .[, yintercept:=cumsum(yintercept), by = .(Category)]

# Plot Percentage 
(pVP <- pV + geom_col(position = position_fill())  + 
    labs(y = "Sell-Out Val. % ") +    
    geom_hline(
      data = x_mean_cumV, 
      mapping= aes(yintercept = yintercept, color = MAP), linetype = "dashed", size = 1) +
    colScale_col +    
    scale_y_continuous(
      labels = scales::percent_format(), breaks = br,
      sec.axis = sec_axis(~ ., labels = scales::percent_format(), breaks = br )))
# save plot per day
ggsave(plot = pVP, 
       file.path(path, paste0(params$opco, "_vp_", today(), ".png")))
```

```{r global_article_mapping, eval=TRUE}
metadata_didp[COLUMN_NAME == "GLOBAL_ARTICLE_NUMBER", DS] %>%
  f_write_global_article_log(raw_data = raw_data)
```

```{r process_tables, eval=TRUE}

f_process_factors <- 
  function(x){
    
    output <- list()    

    output[["value"]]   <- lapply(x, f_get_value)
    output[["pattern"]] <- lapply(x, f_get_pattern)
    output[["word"]]    <- lapply(x, f_get_word)
    output
  }

# output[['store']][['pattern']][['STORE_ID']]
output <- lapply(opco_factors, f_process_factors)
#cardin <- lapply(raw_data, f_calc_cardinality)

```

